### ISSUE TITLE
can you please help me to give the sample input for your code 

### ISSUE THREAD

**Issue by YokeshGithub** [vinodnextcoder/doremi-subscription-geektrust#4]
I want to know how to give the input on the input2.txt and how to take the output can give me some examples or samples for your project it much helpful for me how to run it!

![Screenshot (492)](https://github.com/vinodnextcoder/doremi-subscription-geektrust/assets/111746788/e67be0a4-45c9-4f9a-b7eb-33e6fd251cd2)

**Comment by vinodnextcoder** [comment]
HI you can get this from https://www.geektrust.com/coding/detailed/doremi-subscription

**Comment by YokeshGithub** [comment]
> HI you can get this from https://www.geektrust.com/coding/detailed/doremi-subscription


Yeah I too get from that web site thats okay I have download your project and run it but i want to know how to give the input to your project?

**Comment by vinodnextcoder** [comment]
You have run run.bat file and change input file in run.bat file sample_input/input2.txt like this
or try this
Please fill input1.txt and input2.txt with the input commands and use those files in run.bat or run.sh. Replace ./geektrust sample_input/input1.txt with ./geektrust sample_input/input2.txt to run the test case from the second file.

**Comment by YokeshGithub** [comment]
> You have run run.bat file and change input file in run.bat file sample_input/input2.txt like this or try this Please fill input1.txt and input2.txt with the input commands and use those files in run.bat or run.sh. Replace ./geektrust sample_input/input1.txt with ./geektrust sample_input/input2.txt to run the test case from the second file.




Yes thank you your saying change "Please fill input1.txt and input2.txt with the input commands and use those files in run.bat or run.sh.  " How to fill input1.txt and input2.txt with the input commands and use those files in run.bat or run.sh . how to do it bro do you have any sample or examples? How to fill the input  Any youtube links?

**Comment by vinodnextcoder** [comment]
START_SUBSCRIPTION DD-MM-YYYY 
ADD_SUBSCRIPTION SUBSCRIPTION_CATEGORY PLAN_NAME 
ADD_TOPUP TOP_UP_NAME NO_OF_MONTHS 
PRINT_RENEWAL_DETAILS 

Examples :
START_SUBSCRIPTION 20-02-2022 
ADD_SUBSCRIPTION MUSIC  PERSONAL 
ADD_SUBSCRIPTION VIDEO PREMIUM 
ADD_TOPUP ADD_TOPUP 
PRINT_RENEWAL_DETAILS

**Comment by vinodnextcoder** [comment]
START_SUBSCRIPTION20-02-2022
ADD_SUBSCRIPTIONMUSIC PERSONAL
ADD_SUBSCRIPTIONVIDEO PREMIUM
ADD_SUBSCRIPTIONPODCAST FREE
ADD_TOPUPFOUR_DEVICE 3
PRINT_RENEWAL_DETAILS

**Comment by vinodnextcoder** [comment]
output'
RENEWAL_REMINDERMUSIC 10-03-2022
RENEWAL_REMINDERVIDEO 10-05-2022
RENEWAL_REMINDERPODCAST 10-03-2022
RENEWAL_AMOUNT750

**Comment by YokeshGithub** [comment]
> output' RENEWAL_REMINDERMUSIC 10-03-2022 RENEWAL_REMINDERVIDEO 10-05-2022 RENEWAL_REMINDERPODCAST 10-03-2022 RENEWAL_AMOUNT750


Thanks a lot! Its more helpful for me let me know in your project there is file "sample_input/input2.txt" In this input2.txt file Need to change something else in this file "input2.txt" ?
![Screenshot (493)](https://github.com/vinodnextcoder/doremi-subscription-geektrust/assets/111746788/0eea2139-02a5-41fb-8bcd-836ab487577d)

**Comment by vinodnextcoder** [comment]
you put any which you want run input file

**Comment by YokeshGithub** [comment]
> you put any which you want run input file

Bro give some example for input2.txt like as you given for input1.txt please

**Comment by vinodnextcoder** [comment]
https://github.com/vinodnextcoder/doremi-subscription-geektrust/blob/main/sample_input/input2.txt
updated
